From 55cdab32a92c49405823c0544141bb69acd2d66e Mon Sep 17 00:00:00 2001
From: Tristan Cacqueray <tdecacqu@redhat.com>
Date: Wed, 18 May 2016 09:40:09 -0400
Subject: [PATCH] Add _get_username method to discover username

This change mitigate this exception:
  File "gerritbot/bot.py", line 154, in change_created
    data['patchSet']['uploader']['name'],
KeyError: 'name'

Change-Id: Ia1f394d6ff0e158df16461cf3150761f6ec12f29
---

diff --git a/gerritbot/bot.py b/gerritbot/bot.py
index d024537..d71e7a8 100755
--- a/gerritbot/bot.py
+++ b/gerritbot/bot.py
@@ -148,9 +148,19 @@
             # Delay before attempting again.
             time.sleep(1)
 
+    @staticmethod
+    def _get_username(patchset):
+        # Try to find username
+        username = patchset['uploader'].get('name')
+        if not username:
+            username = patchset['uploader'].get('username')
+            if not username:
+                username = patchset['uploader'].get('email')
+        return username
+
     def patchset_created(self, channel, data):
         msg = '%s proposed %s: %s  %s' % (
-            data['patchSet']['uploader']['name'],
+            self._get_username(data['patchSet']),
             data['change']['project'],
             data['change']['subject'],
             data['change']['url'])
